import { db } from "@/db";
import {
  builders,
  properties,
  propertyImages,
  leads,
  admins,
} from "@/db/schema";
import { hashPassword } from "./auth";
import { createSlug } from "./queries";

const BUILDER_PASSWORD = "Builder@123";
const ADMIN_PASSWORD = "Admin@123";

const builderSeed = [
  {
    name: "Sravanthi Constructions",
    email: "contact@sravanthi.com",
    phone: "+91 9876543210",
    description:
      "Sravanthi Constructions is a leading real estate developer in Visakhapatnam with over 25 years of experience building premium apartments, villas and commercial spaces across the city. Known for quality construction, on-time delivery and customer-first approach.",
    logo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&h=200&fit=crop",
    website: "https://sravanthi.com",
    address: "MVP Colony, Visakhapatnam",
    experienceYears: 25,
    projectsCount: 40,
    isVerified: true,
  },
  {
    name: "Anand Vihar Builders",
    email: "info@anandvihar.com",
    phone: "+91 9876511220",
    description:
      "Anand Vihar Builders has been shaping the skyline of Vizag with thoughtfully designed residential projects. With a focus on sustainability, modern amenities and prime locations, we deliver homes that families love.",
    logo: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=200&h=200&fit=crop",
    website: "https://anandvihar.com",
    address: "Dwaraka Nagar, Visakhapatnam",
    experienceYears: 18,
    projectsCount: 28,
    isVerified: true,
  },
  {
    name: "Vizag Habitat Pvt Ltd",
    email: "hello@vizaghabitat.in",
    phone: "+91 9988776655",
    description:
      "Vizag Habitat is a trusted name in real estate development across coastal Andhra. We specialize in plotted developments, gated community villas and affordable apartments in fast-growing corridors of Vizag.",
    logo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&h=200&fit=crop",
    website: "https://vizaghabitat.in",
    address: "Madhurawada, Visakhapatnam",
    experienceYears: 12,
    projectsCount: 18,
    isVerified: true,
  },
  {
    name: "Suryadev Estates",
    email: "contact@suryadev.in",
    phone: "+91 9090909090",
    description:
      "Suryadev Estates crafts premium independent houses and luxury villas in the most sought-after neighborhoods of Vizag. Every home is built with attention to detail, Vastu-compliance and world-class finishes.",
    logo: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=200&h=200&fit=crop",
    website: "https://suryadev.in",
    address: "Rushikonda, Visakhapatnam",
    experienceYears: 20,
    projectsCount: 32,
    isVerified: true,
  },
  {
    name: "BlueBay Properties",
    email: "info@bluebay.in",
    phone: "+91 9123456789",
    description:
      "BlueBay Properties focuses on commercial real estate and mixed-use developments in Vizag's business districts. From retail spaces to Grade-A offices, we create assets that appreciate in value.",
    logo: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=200&h=200&fit=crop",
    website: "https://bluebay.in",
    address: "Beach Road, Visakhapatnam",
    experienceYears: 15,
    projectsCount: 14,
    isVerified: true,
  },
];

const propertySeed = [
  {
    builderEmail: "contact@sravanthi.com",
    title: "3 BHK Luxury Apartment at MVP Colony",
    propertyType: "apartment",
    status: "ready_to_move",
    furnishing: "semi_furnished",
    price: 9500000,
    pricePerSqft: 5500,
    area: 1720,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 7,
    totalFloors: 12,
    facing: "East",
    address: "Sector 4, MVP Colony, Visakhapatnam, AP 530017",
    location: "MVP Colony",
    pincode: "530017",
    latitude: "17.7385",
    longitude: "83.3350",
    reraId: "APRERA/REG/2024/001234",
    isFeatured: true,
    description:
      "Welcome to a thoughtfully designed 3 BHK luxury apartment in the heart of MVP Colony. Spread across 1,720 sqft on the 7th floor of a premium 12-storey tower, this home offers panoramic city views, abundant natural light and cross-ventilation. The apartment features a spacious living and dining area, modular kitchen with granite countertops, three well-appointed bedrooms with attached bathrooms, two large balconies and dedicated utility spaces. The project includes a 5,000 sqft clubhouse with swimming pool, gym, indoor games, party hall and landscaped gardens. Located within walking distance of top schools, hospitals and shopping centres, this is the perfect home for modern Vizag families.",
    amenities: [
      "Swimming Pool",
      "Gymnasium",
      "Children's Play Area",
      "Clubhouse",
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Landscaped Gardens",
      "Indoor Games Room",
      "Multi-purpose Hall",
    ],
    highlights: [
      "Ready to move-in",
      "RERA registered project",
      "Premium fittings & finishes",
      "Vastu compliant layout",
      "Walking distance to schools & hospitals",
    ],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "contact@sravanthi.com",
    title: "4 BHK Sea View Penthouse at Rushikonda",
    propertyType: "penthouse",
    status: "ready_to_move",
    furnishing: "fully_furnished",
    price: 28000000,
    pricePerSqft: 8000,
    area: 3500,
    bedrooms: 4,
    bathrooms: 5,
    balconies: 3,
    floor: 18,
    totalFloors: 18,
    facing: "West",
    address: "Rushikonda Beach Road, Visakhapatnam, AP 530045",
    location: "Rushikonda",
    pincode: "530045",
    latitude: "17.8295",
    longitude: "83.3850",
    reraId: "APRERA/REG/2023/005678",
    isFeatured: true,
    description:
      "An iconic 4 BHK sea-facing penthouse on the 18th floor with uninterrupted views of the Bay of Bengal. This 3,500 sqft residence is fully furnished with imported fittings, Italian marble flooring, smart home automation and a private terrace pool. The master suite features a walk-in wardrobe and a spa-style bathroom. The building offers concierge services, a rooftop infinity pool, sky lounge, private elevator access and dedicated parking for three cars. A rare opportunity to own a true luxury address in Vizag.",
    amenities: [
      "Private Terrace Pool",
      "Sky Lounge",
      "Concierge Service",
      "Smart Home Automation",
      "Private Elevator",
      "Italian Marble Flooring",
      "Modular Kitchen with Built-in Appliances",
      "Spa & Sauna",
      "24x7 Power Backup",
      "3 Car Reserved Parking",
    ],
    highlights: [
      "Unobstructed sea views",
      "Fully furnished with luxury imports",
      "Private terrace with plunge pool",
      "Top-floor exclusivity",
      "Concierge & valet services",
    ],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "info@anandvihar.com",
    title: "2 BHK Affordable Apartment at Gajuwaka",
    propertyType: "apartment",
    status: "ready_to_move",
    furnishing: "unfurnished",
    price: 3200000,
    pricePerSqft: 3200,
    area: 1000,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    floor: 4,
    totalFloors: 8,
    facing: "North",
    address: "Main Road, Gajuwaka, Visakhapatnam, AP 530026",
    location: "Gajuwaka",
    pincode: "530026",
    latitude: "17.6850",
    longitude: "83.1800",
    reraId: "APRERA/REG/2024/009012",
    isFeatured: true,
    description:
      "A practical and well-planned 2 BHK apartment ideal for first-time homebuyers and young families. The home features a bright living room, separate kitchen, two bedrooms with attached bathrooms, a balcony and a dedicated utility area. The complex offers covered parking, lifts, security, children's play area and a community hall. Located in the heart of Gajuwaka with easy access to the railway station, bus stops, schools and markets.",
    amenities: [
      "Covered Parking",
      "Lift",
      "24x7 Security",
      "Children's Play Area",
      "Community Hall",
      "Power Backup",
      "Rainwater Harvesting",
    ],
    highlights: [
      "Affordable pricing",
      "Ready to move-in",
      "Prime Gajuwaka location",
      "Good rental potential",
      "RERA registered",
    ],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "info@anandvihar.com",
    title: "3 BHK Garden Apartment at Dwaraka Nagar",
    propertyType: "apartment",
    status: "under_construction",
    furnishing: "unfurnished",
    price: 7800000,
    pricePerSqft: 4800,
    area: 1620,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 3,
    totalFloors: 14,
    facing: "East",
    address: "Dwaraka Nagar, Visakhapatnam, AP 530016",
    location: "Dwaraka Nagar",
    pincode: "530016",
    latitude: "17.7150",
    longitude: "83.3100",
    reraId: "APRERA/REG/2024/003456",
    isFeatured: false,
    description:
      "An elegantly designed 3 BHK garden apartment on the 3rd floor with a private garden. The home offers a large living room, dining area, modular kitchen, three bedrooms and two spacious balconies. Project amenities include a clubhouse, gym, swimming pool, jogging track and landscaped gardens. Expected possession by December 2026. Pre-launch offers available for early buyers.",
    amenities: [
      "Private Garden",
      "Swimming Pool",
      "Gymnasium",
      "Clubhouse",
      "Jogging Track",
      "Children's Play Area",
      "Yoga Deck",
      "EV Charging",
    ],
    highlights: [
      "Under construction - possession 2026",
      "Private garden with apartment",
      "Pre-launch offers available",
      "Flexible payment plans",
      "RERA registered",
    ],
    images: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "hello@vizaghabitat.in",
    title: "Residential Plot at Sabbavaram - 200 sqyd",
    propertyType: "plot",
    status: "ready_to_move",
    furnishing: "unfurnished",
    price: 2500000,
    pricePerSqft: 12500,
    area: 1800,
    bedrooms: 0,
    bathrooms: 0,
    balconies: 0,
    facing: "South",
    address: "Sabbavaram Main Road, Visakhapatnam, AP 531035",
    location: "Sabbavaram",
    pincode: "531035",
    latitude: "17.7900",
    longitude: "83.1200",
    reraId: "APRERA/PLOT/2024/00789",
    isFeatured: true,
    description:
      "A 200 sqyd fully developed residential plot in a DTCP-approved layout at Sabbavaram. The plot comes with 40ft and 30ft blacktop internal roads, underground drainage, electricity, water supply and streetlights. The gated community offers 24x7 security, a park, children's play area and a community hall. HMDA/RERA approved layout with clear title. Ideal for building your dream home in a fast-growing corridor of Vizag.",
    amenities: [
      "DTCP Approved Layout",
      "24x7 Security",
      "Underground Drainage",
      "Underground Electricity",
      "Water Supply",
      "Blacktop Roads",
      "Children's Park",
      "Community Hall",
    ],
    highlights: [
      "DTCP approved & RERA registered",
      "Clear title & ready for construction",
      "Located in growth corridor",
      "40ft & 30ft blacktop roads",
      "Excellent appreciation potential",
    ],
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "hello@vizaghabitat.in",
    title: "300 sqyd Premium Plot at Kommadi",
    propertyType: "plot",
    status: "ready_to_move",
    furnishing: "unfurnished",
    price: 4500000,
    pricePerSqft: 15000,
    area: 2700,
    bedrooms: 0,
    bathrooms: 0,
    balconies: 0,
    facing: "East",
    address: "Kommadi Junction, Visakhapatnam, AP 530024",
    location: "Kommadi",
    pincode: "530024",
    latitude: "17.8200",
    longitude: "83.3900",
    reraId: "APRERA/PLOT/2024/00555",
    isFeatured: false,
    description:
      "A premium 300 sqyd corner plot in a fully developed gated layout at Kommadi. Excellent connectivity to IT corridor, schools, hospitals and the new international airport. The layout has wide 60ft main road, 40ft internal roads, landscaped parks, rainwater harvesting and solar-powered common areas. Perfect for building a luxury villa.",
    amenities: [
      "Corner Plot",
      "60ft Main Road",
      "Gated Community",
      "Landscaped Parks",
      "Solar Common Areas",
      "Rainwater Harvesting",
      "24x7 Security",
    ],
    highlights: [
      "Premium gated layout",
      "Near IT corridor",
      "Corner plot advantage",
      "World-class infrastructure",
      "High appreciation zone",
    ],
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "contact@suryadev.in",
    title: "4 BHK Independent Villa at Yendada",
    propertyType: "villa",
    status: "ready_to_move",
    furnishing: "semi_furnished",
    price: 18500000,
    pricePerSqft: 6500,
    area: 2850,
    bedrooms: 4,
    bathrooms: 5,
    balconies: 3,
    floor: 2,
    totalFloors: 2,
    facing: "North",
    address: "Yendada, Visakhapatnam, AP 530045",
    location: "Yendada",
    pincode: "530045",
    latitude: "17.8400",
    longitude: "83.4000",
    reraId: "APRERA/VILLA/2024/00222",
    isFeatured: true,
    description:
      "A stunning 4 BHK independent villa in a private gated community of 12 homes at Yendada. Built on a 350 sqyd plot with a 2,850 sqft built-up area across ground and first floors. The villa features a private garden, covered sit-out, spacious living and dining, modular kitchen, four bedrooms with attached bathrooms, a study, family lounge and servant quarters. Premium fittings, imported tiles, video door phone and home automation. A tranquil address with easy access to the IT corridor.",
    amenities: [
      "Private Garden",
      "Covered Sit-out",
      "Servant Quarter",
      "Home Automation",
      "Video Door Phone",
      "Modular Kitchen",
      "CCTV Security",
      "Solar Heater",
      "Power Backup",
    ],
    highlights: [
      "Private gated community of 12 villas",
      "Premium fittings & finishes",
      "350 sqyd plot, 2850 sqft built-up",
      "Servant quarter included",
      "Near IT corridor",
    ],
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "contact@suryadev.in",
    title: "5 BHK Beach Villa at Bheemunipatnam",
    propertyType: "villa",
    status: "new_launch",
    furnishing: "fully_furnished",
    price: 45000000,
    pricePerSqft: 12000,
    area: 3750,
    bedrooms: 5,
    bathrooms: 6,
    balconies: 4,
    floor: 2,
    totalFloors: 2,
    facing: "West",
    address: "Bheemunipatnam Beach Road, Visakhapatnam, AP 531163",
    location: "Bheemunipatnam",
    pincode: "531163",
    latitude: "17.8860",
    longitude: "83.4520",
    reraId: "APRERA/VILLA/2024/00999",
    isFeatured: true,
    description:
      "A breathtaking 5 BHK beachfront villa on the pristine shores of Bheemunipatnam. The 3,750 sqft fully furnished villa sits on a 500 sqyd plot with direct beach access, an infinity-edge pool overlooking the Bay of Bengal, private landscaped gardens and a rooftop entertainment deck. Italian marble, smart home automation, designer lighting, private elevator and an outdoor kitchen make this a true luxury retreat. The villa is part of a 6-villa private estate with 24x7 security and concierge services.",
    amenities: [
      "Private Beach Access",
      "Infinity Pool",
      "Rooftop Deck",
      "Private Elevator",
      "Smart Home Automation",
      "Designer Kitchen",
      "Outdoor BBQ Kitchen",
      "Concierge Service",
      "Italian Marble",
    ],
    highlights: [
      "Direct beachfront with private access",
      "Infinity pool overlooking the Bay",
      "Fully furnished with luxury imports",
      "Private estate of only 6 villas",
      "Concierge & butler services",
    ],
    images: [
      "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1613553497126-a44624272024?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "info@bluebay.in",
    title: "Commercial Office Space at Dwaraka Nagar",
    propertyType: "commercial",
    status: "ready_to_move",
    furnishing: "fully_furnished",
    price: 12500000,
    pricePerSqft: 7500,
    area: 1665,
    bedrooms: 0,
    bathrooms: 2,
    balconies: 0,
    floor: 5,
    totalFloors: 8,
    facing: "East",
    address: "Dwaraka Nagar Main Road, Visakhapatnam, AP 530016",
    location: "Dwaraka Nagar",
    pincode: "530016",
    latitude: "17.7150",
    longitude: "83.3100",
    reraId: "APRERA/COMM/2024/00333",
    isFeatured: false,
    description:
      "A premium fully furnished Grade-A office space of 1,665 sqft on the 5th floor of a commercial tower in Dwaraka Nagar. The space includes a reception area, two conference rooms, individual cabins, an open work area, pantry, server room and two restrooms. Building amenities include 24x7 security, multiple lifts, fire-fighting systems, power backup and reserved parking. Ideal for IT, consulting and corporate offices.",
    amenities: [
      "Fully Furnished",
      "Conference Rooms",
      "Pantry",
      "Server Room",
      "24x7 Security",
      "Power Backup",
      "Fire Safety",
      "Reserved Parking",
    ],
    highlights: [
      "Grade-A commercial tower",
      "Fully furnished and ready",
      "Prime Dwaraka Nagar location",
      "Reserved parking included",
      "Suitable for IT / corporate",
    ],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "info@bluebay.in",
    title: "Retail Showroom at Beach Road",
    propertyType: "commercial",
    status: "ready_to_move",
    furnishing: "unfurnished",
    price: 18000000,
    pricePerSqft: 15000,
    area: 1200,
    bedrooms: 0,
    bathrooms: 1,
    balconies: 0,
    floor: 1,
    totalFloors: 4,
    facing: "West",
    address: "Beach Road, Visakhapatnam, AP 530001",
    location: "Beach Road",
    pincode: "530001",
    latitude: "17.7230",
    longitude: "83.3280",
    reraId: "APRERA/COMM/2024/00444",
    isFeatured: true,
    description:
      "A high-visibility 1,200 sqft ground-floor retail showroom on Beach Road, one of Vizag's most prestigious commercial addresses. Double-height glass frontage, 12-foot ceiling, 30-foot frontage and high footfall make this an ideal location for premium retail brands, banks, restaurants and showrooms. Includes dedicated parking, signage rights and 24x7 access.",
    amenities: [
      "Ground Floor",
      "Double-height Glass Frontage",
      "12ft Ceiling",
      "30ft Frontage",
      "Dedicated Parking",
      "Signage Rights",
      "24x7 Access",
    ],
    highlights: [
      "Premium Beach Road address",
      "High footfall area",
      "Ground floor retail",
      "Brand signage rights",
      "Excellent for retail / banks / F&B",
    ],
    images: [
      "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1604754742629-3e5728249d73?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "contact@sravanthi.com",
    title: "Independent House at Pendurthi - 4 BHK",
    propertyType: "independent_house",
    status: "ready_to_move",
    furnishing: "semi_furnished",
    price: 7500000,
    pricePerSqft: 4500,
    area: 1665,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 2,
    floor: 2,
    totalFloors: 2,
    facing: "East",
    address: "Pendurthi, Visakhapatnam, AP 531173",
    location: "Pendurthi",
    pincode: "531173",
    latitude: "17.8050",
    longitude: "83.2050",
    reraId: "APRERA/HOUSE/2024/00666",
    isFeatured: false,
    description:
      "A spacious 4 BHK independent house on a 200 sqyd plot in a quiet residential colony at Pendurthi. Ground floor: living room, dining, kitchen, one bedroom and one bathroom. First floor: three bedrooms with attached bathrooms, balcony and family lounge. The house has covered parking for two cars, a private garden, borewell and overhead tank. Ideal for large families looking for independent living with good connectivity to the airport and IT corridor.",
    amenities: [
      "Private Garden",
      "Covered Parking (2 cars)",
      "Borewell",
      "Overhead Tank",
      "Modular Kitchen",
      "Vastu Compliant",
      "CCTV",
    ],
    highlights: [
      "Independent house with private garden",
      "200 sqyd plot, 1665 sqft built-up",
      "Vastu compliant",
      "Good connectivity to airport & IT",
      "Ready to move-in",
    ],
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1600&h=1000&fit=crop",
    ],
  },
  {
    builderEmail: "info@anandvihar.com",
    title: "3 BHK Apartment at Madhurawada",
    propertyType: "apartment",
    status: "new_launch",
    furnishing: "unfurnished",
    price: 6500000,
    pricePerSqft: 4200,
    area: 1550,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 5,
    totalFloors: 15,
    facing: "West",
    address: "Madhurawada, Visakhapatnam, AP 530048",
    location: "Madhurawada",
    pincode: "530048",
    latitude: "17.8200",
    longitude: "83.3700",
    reraId: "APRERA/REG/2024/00777",
    isFeatured: true,
    description:
      "Brand new launch - 3 BHK premium apartments at Madhurawada, Vizag's fastest growing residential hub. Spread across 1,550 sqft, the homes offer spacious layouts, large balconies and stunning hill views. The 15-storey tower includes a grand clubhouse, infinity pool, sky garden, co-working space, gym and kids' zone. Walking distance to IT companies, schools and the proposed metro. Book now at pre-launch prices.",
    amenities: [
      "Infinity Pool",
      "Sky Garden",
      "Co-working Space",
      "Gym",
      "Kids' Zone",
      "Clubhouse",
      "EV Charging",
      "CCTV & Security",
    ],
    highlights: [
      "New launch - pre-launch prices",
      "Near IT corridor & metro",
      "Premium 15-storey tower",
      "Hill view apartments",
      "RERA registered",
    ],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1600&h=1000&fit=crop",
    ],
  },
];

export async function seedDatabase() {
  console.log("🌱 Seeding database...");

  // Check if already seeded
  const existingBuilders = await db.select().from(builders).limit(1);
  if (existingBuilders.length > 0) {
    console.log("✅ Database already seeded, skipping.");
    return;
  }

  // Create admin
  const adminPasswordHash = await hashPassword(ADMIN_PASSWORD);
  await db.insert(admins).values({
    name: "Vizag Properties Admin",
    email: "admin@vizag.properties",
    passwordHash: adminPasswordHash,
    role: "admin",
  });
  console.log("✅ Created admin: admin@vizag.properties / Admin@123");

  // Create builders
  const builderPasswordHash = await hashPassword(BUILDER_PASSWORD);
  const builderMap: Record<string, number> = {};

  for (const b of builderSeed) {
    const slug = createSlug(b.name);
    const [inserted] = await db
      .insert(builders)
      .values({
        name: b.name,
        slug,
        email: b.email,
        phone: b.phone,
        passwordHash: builderPasswordHash,
        description: b.description,
        logo: b.logo,
        website: b.website,
        address: b.address,
        experienceYears: b.experienceYears,
        projectsCount: b.projectsCount,
        isVerified: b.isVerified,
        isActive: true,
      })
      .returning();
    builderMap[b.email] = inserted.id;
    console.log(`✅ Created builder: ${b.name}`);
  }

  // Create properties
  for (const p of propertySeed) {
    const builderId = builderMap[p.builderEmail];
    if (!builderId) continue;

    const slug = createSlug(p.title);
    const [insertedProperty] = await db
      .insert(properties)
      .values({
        builderId,
        title: p.title,
        slug,
        description: p.description,
        propertyType: p.propertyType as any,
        status: p.status as any,
        furnishing: p.furnishing as any,
        price: p.price,
        pricePerSqft: p.pricePerSqft,
        area: p.area,
        bedrooms: p.bedrooms,
        bathrooms: p.bathrooms,
        balconies: p.balconies,
        floor: p.floor,
        totalFloors: p.totalFloors,
        facing: p.facing,
        address: p.address,
        location: p.location,
        city: "Visakhapatnam",
        state: "Andhra Pradesh",
        pincode: p.pincode,
        latitude: p.latitude,
        longitude: p.longitude,
        amenities: p.amenities,
        highlights: p.highlights,
        reraId: p.reraId,
        isFeatured: p.isFeatured,
        isActive: true,
      })
      .returning();

    for (let i = 0; i < p.images.length; i++) {
      await db.insert(propertyImages).values({
        propertyId: insertedProperty.id,
        imageUrl: p.images[i],
        altText: `${p.title} - Image ${i + 1}`,
        isCover: i === 0,
        sortOrder: i,
      });
    }
    console.log(`✅ Created property: ${p.title}`);
  }

  // Create a few sample leads
  await db.insert(leads).values([
    {
      name: "Ravi Kumar",
      phone: "+91 9876543210",
      email: "ravi.kumar@example.com",
      budget: "₹ 80 L - 1 Cr",
      preferredLocation: "MVP Colony",
      propertyType: "apartment",
      message: "Looking for a 3 BHK ready to move apartment in MVP Colony.",
      source: "homepage",
      status: "new",
    },
    {
      name: "Priya Sharma",
      phone: "+91 9123456780",
      email: "priya.sharma@example.com",
      budget: "₹ 1.5 Cr - 2 Cr",
      preferredLocation: "Rushikonda",
      propertyType: "villa",
      message: "Interested in 4 BHK villas with sea view.",
      source: "property_details",
      status: "contacted",
    },
    {
      name: "Anil Reddy",
      phone: "+91 9988776655",
      email: "anil.reddy@example.com",
      budget: "₹ 30 L - 50 L",
      preferredLocation: "Sabbavaram",
      propertyType: "plot",
      message: "Need a 200 sqyd plot for investment.",
      source: "properties_page",
      status: "qualified",
    },
  ]);
  console.log("✅ Created sample leads");

  console.log("🎉 Database seeded successfully!");
  console.log("\n📝 Login Credentials:");
  console.log("Admin: admin@vizag.properties / Admin@123");
  console.log("Builder: contact@sravanthi.com / Builder@123");
}
